import { CONFIG_PATH } from './constants.js';

export const printUsage = (): void => {
    const lines = [
        'es <command> [options]',
        '',
        'Commands:',
        '  config show',
        '  config clear',
        '  config set api-key <value>',
        '  config set base-url <value>',
        '  config set range <7d|30d|90d|YYYY-MM-DD..YYYY-MM-DD>',
        '',
        '  keywords list [--search <text>] [--tracking-state <state>] [--sync-state <state>] [--limit <n>] [--offset <n>]',
        '  keywords track <keyword>',
        '',
        '  listings list [--search <text>] [--tracking-state <state>] [--sync-state <state>] [--show-digital] [--limit <n>] [--offset <n>]',
        '  listings track <listing_id|listing_url>',
        '  listings performance <tracked_listing_id> [--range <7d|30d|90d|YYYY-MM-DD..YYYY-MM-DD>]',
        '    [--metrics <views,favorites,quantity,price>] [--mode <table|metrics>]',
        '',
        '  shops list [--search <text>] [--tracking-state <state>] [--sync-state <state>] [--limit <n>] [--offset <n>]',
        '  shops track <shop_id|shop_url|shop_name>',
        '',
        'Aliases:',
        '  track keyword -> keywords track',
        '  track listing -> listings track',
        '  track product -> listings track',
        '  track shop -> shops track',
        '  products ... -> listings ...',
        '',
        'Options:',
        '  -h, --help                 Show this message',
        '  --api-key <value>          Override API key for this command',
        '  --base-url <url>           Override API base URL for this command',
        '  --search <text>            List filter text',
        '  --tracking-state <state>   List filter tracking state',
        '  --sync-state <state>       List filter sync state',
        '  --show-digital             Include digital listings in listings list',
        '  --limit <n>                Max number of list results after filters',
        '  --offset <n>               Number of filtered list results to skip',
        '  --range <value>            Performance range override',
        '  --metrics <csv>            Performance metrics selection',
        '  --mode <metrics|table>     Performance output mode',
        '',
        'Config file:',
        `  ${CONFIG_PATH}`,
        '',
        'Env fallbacks:',
        '  ETSYSENTRY_API_KEY',
        '  ETSYSENTRY_API_BASE_URL',
        '  ETSYSENTRY_DEFAULT_RANGE',
    ];

    console.log(lines.join('\n'));
};
